/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Graphics;
import java.util.ArrayList;
import modelo.Monedas;
import modelo.Sapo;

/**
 *
 * @author Roy
 */
public class PanelFondo extends javax.swing.JPanel {

    
private Sapo sapo;
private ArrayList<Monedas> listaMonedas = new ArrayList<>();
    
   
    
    public PanelFondo() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

//      @Override
//    public void paint(Graphics g)
//    { 
//        ImageIcon fondo = new ImageIcon(getClass().getResource("/img/fondoMario.jpg")); 
//       
//        g.drawImage(fondo.getImage(), 0, 0, getWidth(), getHeight(), this);
//        
//        setOpaque(false); // le indica al panel que no dibuje su fondo por defecto
//        
//        super.paintComponent(g); // le indica al panel que puede seguir dibujando el resto de los componentes
//    }
      
      
      
    public void setSapo(Sapo sapo)
    {
        this.sapo = sapo;
    }
    
    public void setMonedas(ArrayList<Monedas> monedas)
    {
        this.listaMonedas = monedas;
    }
      
   
@Override
    public void paint(Graphics g)
    {
        super.paint(g);
        
        if(sapo!=null)
        {
            sapo.dibujarSapo(g);
        }
        
        for(Monedas monedaAux : listaMonedas)
        {
            if(monedaAux!=null)
                monedaAux.dibujarMoneda(g);
        }
    }


}
